"use client";

import { useCallback, useEffect, useState } from "react";
import { callAdminAction } from "@/lib/callAdminAction";
import { createSupplier, listSuppliers } from "@/app/admin/proveedores/actions";
import type { AdminSupplierDTO } from "@/lib/purchaseAdmin/types";

export default function ProveedoresPage(){
  const [items,setItems]=useState<AdminSupplierDTO[]>([]); const [query,setQuery]=useState(""); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [showForm,setShowForm]=useState(false);
  const [name,setName]=useState(""); const [documentType,setDocumentType]=useState("NIT"); const [documentNumber,setDocumentNumber]=useState(""); const [contactName,setContactName]=useState(""); const [phone,setPhone]=useState(""); const [email,setEmail]=useState(""); const [address,setAddress]=useState(""); const [city,setCity]=useState("Bogotá"); const [notes,setNotes]=useState("");
  const load=useCallback(async(q="")=>{try{setLoading(true);setError("");const r=await callAdminAction(listSuppliers,{query:q,limit:200});if(!r.ok){setError("No fue posible cargar proveedores.");return;}setItems(r.data.items);}catch{setError("No fue posible cargar proveedores.");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const submit=async()=>{if(saving||name.trim().length<2)return;try{setSaving(true);setError("");setMessage("");const r=await callAdminAction(createSupplier,{name,documentType:documentType.trim()||undefined,documentNumber:documentNumber.trim()||undefined,contactName:contactName.trim()||undefined,phone:phone.trim()||undefined,email:email.trim()||undefined,address:address.trim()||undefined,city:city.trim()||undefined,notes:notes.trim()||undefined});if(!r.ok){setError(r.error==="VALIDATION_ERROR"?r.issues.join(" "):"No fue posible crear el proveedor.");return;}setMessage(`${r.data.name} quedó registrado como proveedor.`);setName("");setDocumentNumber("");setContactName("");setPhone("");setEmail("");setAddress("");setNotes("");setShowForm(false);await load(query);}catch{setError("No fue posible crear el proveedor.");}finally{setSaving(false);}};
  return <div className="space-y-6">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-widest text-primary">ERP · Compras</p><h1 className="text-2xl font-bold text-text">Proveedores</h1><p className="mt-1 text-sm text-muted">Fuente canónica de quién suministra cada lote. Las compras conservan snapshots históricos.</p></div><button onClick={()=>setShowForm(v=>!v)} className="rounded-xl bg-primary px-5 py-3 text-sm font-semibold text-white">+ Nuevo proveedor</button></div>
    {message?<p className="rounded-xl border border-green-100 bg-green-50 px-4 py-3 text-sm text-green-700">{message}</p>:null}{error?<p className="rounded-xl border border-red-100 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>:null}
    {showForm?<section className="space-y-4 rounded-2xl border border-border bg-white p-5"><h2 className="font-semibold text-text">Registrar proveedor</h2><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm"><span className="mb-1 block font-medium">Nombre *</span><input value={name} onChange={e=>setName(e.target.value)} maxLength={160} className="w-full rounded-xl border border-border px-4 py-3"/></label><label className="text-sm"><span className="mb-1 block font-medium">Contacto</span><input value={contactName} onChange={e=>setContactName(e.target.value)} className="w-full rounded-xl border border-border px-4 py-3"/></label><div className="grid grid-cols-3 gap-2 sm:col-span-2"><label className="text-sm"><span className="mb-1 block font-medium">Tipo</span><input value={documentType} onChange={e=>setDocumentType(e.target.value)} className="w-full rounded-xl border border-border px-4 py-3"/></label><label className="col-span-2 text-sm"><span className="mb-1 block font-medium">Documento / NIT</span><input value={documentNumber} onChange={e=>setDocumentNumber(e.target.value)} className="w-full rounded-xl border border-border px-4 py-3"/></label></div><label className="text-sm"><span className="mb-1 block font-medium">Celular</span><input value={phone} onChange={e=>setPhone(e.target.value)} className="w-full rounded-xl border border-border px-4 py-3"/></label><label className="text-sm"><span className="mb-1 block font-medium">Correo</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} className="w-full rounded-xl border border-border px-4 py-3"/></label><label className="text-sm"><span className="mb-1 block font-medium">Ciudad</span><input value={city} onChange={e=>setCity(e.target.value)} className="w-full rounded-xl border border-border px-4 py-3"/></label><label className="text-sm"><span className="mb-1 block font-medium">Dirección</span><input value={address} onChange={e=>setAddress(e.target.value)} className="w-full rounded-xl border border-border px-4 py-3"/></label></div><label className="block text-sm"><span className="mb-1 block font-medium">Notas</span><textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={2} className="w-full rounded-xl border border-border px-4 py-3"/></label><div className="flex justify-end gap-2"><button onClick={()=>setShowForm(false)} className="rounded-xl border border-border px-4 py-2.5 text-sm font-semibold">Cancelar</button><button disabled={saving||name.trim().length<2} onClick={()=>void submit()} className="rounded-xl bg-primary px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-40">{saving?"Guardando...":"Guardar proveedor"}</button></div></section>:null}
    <form onSubmit={e=>{e.preventDefault();void load(query);}} className="flex gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar nombre, NIT, contacto, celular o ciudad" className="flex-1 rounded-xl border border-border px-4 py-3 text-sm"/><button className="rounded-xl border border-primary px-5 py-3 text-sm font-semibold text-primary">Buscar</button></form>
    {loading?<p className="text-sm text-muted">Cargando...</p>:null}<div className="grid gap-3 lg:grid-cols-2">{items.map(s=><article key={s.id} className="rounded-2xl border border-border bg-white p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold text-text">{s.name}</h2><p className="text-xs text-muted">{[s.documentType,s.documentNumber].filter(Boolean).join(" ")||"Sin documento"}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${s.active?"bg-green-50 text-green-700":"bg-slate-100 text-slate-600"}`}>{s.active?"Activo":"Inactivo"}</span></div><div className="mt-3 grid gap-1 text-sm"><p><span className="text-muted">Contacto:</span> {s.contactName??"—"}</p><p><span className="text-muted">Celular:</span> {s.phone??"—"}</p><p><span className="text-muted">Correo:</span> {s.email??"—"}</p><p><span className="text-muted">Ciudad:</span> {s.city??"—"}</p></div></article>)}</div>
  </div>;
}
