"use client";
import{useCallback,useEffect,useMemo,useState}from"react";import{callAdminAction}from"@/lib/callAdminAction";import{addCashMovement,closeCash,getCashDashboard,openCash,reverseCashMovement}from"@/app/admin/caja/actions";import{formatCOP}from"@/lib/personalizadorUi";import type{CashMovementDTO,CashSessionDTO,PaymentMethod}from"@/lib/adminPhase2/types";
const METHODS:PaymentMethod[]=["efectivo","transferencia","nequi","daviplata","tarjeta","otro"];
export default function CajaPage(){const[open,setOpen]=useState<CashSessionDTO|null>(null);const[movements,setMovements]=useState<CashMovementDTO[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[message,setMessage]=useState("");const load=useCallback(async()=>{setLoading(true);const r=await callAdminAction(getCashDashboard,{});if(r.ok){setOpen(r.data.open);setMovements(r.data.movements);}else setError("No fue posible cargar caja.");setLoading(false);},[]);useEffect(()=>{void load();},[load]);
const sessionCash=useMemo(()=>open?open.openingCashCop+movements.filter(m=>m.sessionId===open.id&&m.paymentMethod==="efectivo").reduce((s,m)=>s+m.amountCop,0):0,[open,movements]);const totals=useMemo(()=>Object.fromEntries(METHODS.map(x=>[x,movements.reduce((s,m)=>s+(m.paymentMethod===x?m.amountCop:0),0)])),[movements]);
const openSession=async()=>{const amount=Number(prompt("Efectivo inicial en caja (COP):","0"));if(!Number.isInteger(amount)||amount<0)return;const notes=prompt("Nota de apertura (opcional):")??"";const r=await callAdminAction(openCash,{openingCashCop:amount,notes});if(!r.ok)return setError(r.error==="VALIDATION_ERROR"?r.issues.join(" "):"No se pudo abrir caja.");setMessage("Caja abierta.");await load();};
const closeSession=async()=>{if(!open)return;const amount=Number(prompt(`Efectivo contado. Esperado: ${formatCOP(sessionCash)}`,String(sessionCash)));if(!Number.isInteger(amount)||amount<0)return;const notes=prompt("Nota de cierre (opcional):")??"";const r=await callAdminAction(closeCash,{sessionId:open.id,countedCashCop:amount,notes});if(!r.ok)return setError(r.error==="VALIDATION_ERROR"?r.issues.join(" "):"No se pudo cerrar caja.");setMessage("Caja cerrada.");await load();};
const add=async()=>{const type=prompt("Tipo: manual_in | manual_out | purchase_payment","manual_out")?.trim();if(!type||!["manual_in","manual_out","purchase_payment"].includes(type))return;const method=prompt(`Método: ${METHODS.join(" | ")}`,"efectivo")?.trim();if(!method||!METHODS.includes(method as PaymentMethod))return;const amount=Number(prompt("Valor COP:")??"");const description=prompt("Descripción:")?.trim();if(!Number.isInteger(amount)||amount<=0||!description)return;let purchaseId:string|undefined;if(type==="purchase_payment"){purchaseId=prompt("UUID de la compra COMP (desde detalle de compra):")?.trim()||undefined;}const r=await callAdminAction(addCashMovement,{movementType:type,paymentMethod:method,amountCop:amount,description,purchaseId});if(!r.ok)return setError(r.error==="VALIDATION_ERROR"?r.issues.join(" "):"No se pudo registrar movimiento.");setMessage("Movimiento registrado.");await load();};
const reverse=async(m:CashMovementDTO)=>{const reason=prompt(`Motivo para reversar ${m.movementNumber}:`)?.trim();if(!reason)return;const r=await callAdminAction(reverseCashMovement,{movementId:m.id,reason});if(!r.ok)return setError("Este movimiento no admite reverso manual o ya fue reversado.");setMessage("Reverso registrado.");await load();};
return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-widest text-primary">ERP · Fase 2A</p><h1 className="text-2xl font-bold text-text">Caja y flujo de dinero</h1><p className="mt-1 text-sm text-muted">El efectivo se cuadra por sesión. Los demás métodos permanecen en el flujo financiero sin afectar el conteo físico.</p></div><div className="flex gap-2">{open?<button onClick={()=>void closeSession()} className="rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-white">Cerrar caja</button>:<button onClick={()=>void openSession()} className="rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-white">Abrir caja</button>}<button onClick={()=>void add()} className="rounded-xl border border-border px-4 py-2.5 text-sm font-semibold">+ Movimiento</button></div></div>{message?<p className="rounded-xl bg-green-50 p-3 text-sm text-green-700">{message}</p>:null}{error?<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}
<div className="grid gap-3 sm:grid-cols-3"><Card label="Sesión" value={open?.sessionNumber??"Cerrada"}/><Card label="Efectivo esperado" value={open?formatCOP(sessionCash):"—"}/><Card label="Apertura" value={open?formatCOP(open.openingCashCop):"—"}/></div><div className="grid gap-2 sm:grid-cols-3 lg:grid-cols-6">{METHODS.map(x=><Card key={x} label={x} value={formatCOP(Number(totals[x]??0))}/>)}</div>{loading?<p className="text-sm text-muted">Cargando...</p>:null}<div className="overflow-x-auto rounded-2xl border border-border bg-white"><table className="w-full text-sm"><thead className="bg-surface text-left text-xs text-muted"><tr><th className="p-3">Movimiento</th><th>Método</th><th>Descripción</th><th className="text-right">Valor</th><th></th></tr></thead><tbody>{movements.map(m=><tr key={m.id} className="border-t border-border"><td className="p-3 font-mono text-xs">{m.movementNumber}</td><td>{m.paymentMethod}</td><td>{m.description}</td><td className={`text-right font-semibold ${m.amountCop<0?"text-red-600":"text-green-700"}`}>{formatCOP(m.amountCop)}</td><td className="px-3 text-right">{!["sale","expense","reversal"].includes(m.movementType)&&!m.reversalOfId?<button onClick={()=>void reverse(m)} className="text-xs font-semibold text-red-600">Reversar</button>:null}</td></tr>)}</tbody></table></div></div>}
function Card({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-border bg-white p-4"><p className="text-xs font-semibold uppercase text-muted">{label}</p><p className="mt-2 text-xl font-bold text-text">{value}</p></div>}
