"use client";
import{useCallback,useEffect,useMemo,useState}from"react";import{callAdminAction}from"@/lib/callAdminAction";import{createExpense,listExpenses,voidExpense}from"@/app/admin/gastos/actions";import{formatCOP}from"@/lib/personalizadorUi";import type{ExpenseCategory,ExpenseDTO,PaymentMethod}from"@/lib/adminPhase2/types";
const CATS:ExpenseCategory[]=["arriendo","servicios","publicidad","nomina","transporte","hosting","software","papeleria","impuestos","mantenimiento","otro"];const METHODS:PaymentMethod[]=["efectivo","transferencia","nequi","daviplata","tarjeta","otro"];
function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"America/Bogota"}).format(new Date());}
export default function GastosPage(){const[items,setItems]=useState<ExpenseDTO[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[message,setMessage]=useState("");const load=useCallback(async()=>{setLoading(true);const r=await callAdminAction(listExpenses,{limit:150});if(r.ok)setItems(r.data.items);else setError("No fue posible cargar gastos.");setLoading(false);},[]);useEffect(()=>{void load();},[load]);const activeTotal=useMemo(()=>items.filter(x=>x.status==="active").reduce((s,x)=>s+x.amountCop,0),[items]);
const add=async()=>{const category=prompt(`Categoría: ${CATS.join(" | ")}`,"publicidad")?.trim() as ExpenseCategory|undefined;if(!category||!CATS.includes(category))return;const description=prompt("Descripción del gasto:")?.trim();if(!description)return;const amount=Number(prompt("Valor COP:")??"");if(!Number.isInteger(amount)||amount<=0)return;const paymentMethod=prompt(`Método: ${METHODS.join(" | ")}`,"transferencia")?.trim() as PaymentMethod|undefined;if(!paymentMethod||!METHODS.includes(paymentMethod))return;const payee=prompt("Beneficiario/proveedor (opcional):")?.trim()||undefined;const receiptUrl=prompt("URL comprobante http/https (opcional):")?.trim()||undefined;const r=await callAdminAction(createExpense,{category,description,amountCop:amount,paymentMethod,payee,receiptUrl,occurredOn:today()});if(!r.ok)return setError(r.error==="VALIDATION_ERROR"?r.issues.join(" "):"No se pudo registrar el gasto.");setMessage("Gasto registrado y reflejado en flujo de dinero.");await load();};
const cancel=async(x:ExpenseDTO)=>{const reason=prompt(`Motivo para anular ${x.expenseNumber}:`)?.trim();if(!reason)return;const r=await callAdminAction(voidExpense,{expenseId:x.id,reason});if(!r.ok)return setError(r.error==="VALIDATION_ERROR"?r.issues.join(" "):"No se pudo anular.");setMessage("Gasto anulado mediante movimiento compensatorio.");await load();};
return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-widest text-primary">ERP · Fase 2B</p><h1 className="text-2xl font-bold text-text">Gastos operativos</h1><p className="mt-1 text-sm text-muted">Arriendo, publicidad, nómina, servicios, software y demás costos del negocio separados del costo de cada STU.</p></div><button onClick={()=>void add()} className="rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-white">+ Registrar gasto</button></div>{message?<p className="rounded-xl bg-green-50 p-3 text-sm text-green-700">{message}</p>:null}{error?<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}<div className="grid gap-3 sm:grid-cols-3"><Card label="Gastos activos visibles" value={String(items.filter(x=>x.status==="active").length)}/><Card label="Total activo cargado" value={formatCOP(activeTotal)}/><Card label="Anulados" value={String(items.filter(x=>x.status==="voided").length)}/></div>{loading?<p className="text-sm text-muted">Cargando...</p>:null}<div className="space-y-3">{items.map(x=><article key={x.id} className={`rounded-2xl border border-border bg-white p-5 ${x.status==="voided"?"opacity-60":""}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-xs font-bold text-primary">{x.expenseNumber}</p><h2 className="mt-1 font-semibold text-text">{x.description}</h2><p className="text-xs text-muted">{x.category} · {x.paymentMethod} · {x.occurredOn}{x.payee?` · ${x.payee}`:""}</p></div><p className="text-lg font-bold text-red-600">{formatCOP(x.amountCop)}</p></div><div className="mt-3 flex items-center justify-between gap-3">{x.receiptUrl?<a href={x.receiptUrl} target="_blank" rel="noreferrer" className="text-xs font-semibold text-primary">Ver comprobante</a>:<span/>}{x.status==="active"?<button onClick={()=>void cancel(x)} className="text-xs font-semibold text-red-600">Anular</button>:<span className="text-xs text-muted">Anulado: {x.voidReason}</span>}</div></article>)}</div></div>}
function Card({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-border bg-white p-4"><p className="text-xs font-semibold uppercase text-muted">{label}</p><p className="mt-2 text-xl font-bold text-text">{value}</p></div>}
