"use client";
import Link from "next/link";
import {useParams} from "next/navigation";
import {useCallback,useEffect,useState} from "react";
import {callAdminAction} from "@/lib/callAdminAction";
import {addCostEntry,getUnitProfitability,reverseCostEntry} from "@/app/admin/rentabilidad/actions";
import {formatCOP} from "@/lib/personalizadorUi";
import type {AdminUnitProfitabilityDTO,CostCategory} from "@/lib/profitabilityAdmin/types";
const LABELS:Record<CostCategory,string>={upgrade:"Upgrade",repair:"Reparación",spare_part:"Repuesto",labor:"Mano de obra",transport:"Transporte",after_sales:"Posventa",sale_fee:"Comisión venta",accessory:"Accesorio",other:"Otro"};
export default function UnitProfitabilityPage(){const{id}=useParams<{id:string}>();const[item,setItem]=useState<AdminUnitProfitabilityDTO|null>(null);const[loading,setLoading]=useState(true);const[working,setWorking]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");const[category,setCategory]=useState<CostCategory>("upgrade");const[description,setDescription]=useState("");const[amount,setAmount]=useState("");const load=useCallback(async()=>{try{setLoading(true);const r=await callAdminAction(getUnitProfitability,{unitId:id});if(!r.ok){setError(r.error==="NOT_FOUND"?"Unidad no encontrada.":"No fue posible calcular la rentabilidad.");return;}setItem(r.data);}catch{setError("No fue posible calcular la rentabilidad.");}finally{setLoading(false);}},[id]);useEffect(()=>{void load();},[load]);
const submit=async()=>{const v=Number(amount);if(working||!description.trim()||!Number.isInteger(v)||v<=0)return;try{setWorking(true);setError("");setMessage("");const r=await callAdminAction(addCostEntry,{scopeType:"unit",scopeId:id,category,description:description.trim(),amountCop:v});if(!r.ok){setError(r.error==="VALIDATION_ERROR"?r.issues.join(" "):"No fue posible registrar el costo.");return;}if("unitId" in r.data)setItem(r.data);setDescription("");setAmount("");setMessage("Costo agregado al STU.");}catch{setError("No fue posible registrar el costo.");}finally{setWorking(false);}};
const reverse=async(costId:string)=>{if(working)return;const reason=window.prompt("Motivo del reverso contable:")?.trim();if(!reason)return;try{setWorking(true);setError("");const r=await callAdminAction(reverseCostEntry,{unitId:id,costEntryId:costId,reason});if(!r.ok){setError(r.error==="VALIDATION_ERROR"?r.issues.join(" "):"No fue posible reversar.");return;}setItem(r.data);setMessage("Reverso registrado. El costo original permanece en el historial.");}catch{setError("No fue posible reversar.");}finally{setWorking(false);}};
if(loading)return <p className="text-sm text-muted">Calculando STU...</p>;if(!item)return <div><p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error||"Unidad no encontrada."}</p></div>;return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-widest text-primary">ERP · Rentabilidad STU</p><h1 className="font-mono text-2xl font-bold text-text">{item.unitCode}</h1><p className="text-sm text-muted">{item.productName} · Serial {item.serialNumber??"sin registrar"}</p></div><div className="flex gap-2"><Link href="/admin/inventario" className="rounded-xl border border-border px-4 py-2 text-sm font-semibold">Inventario</Link><Link href="/admin/rentabilidad" className="rounded-xl border border-border px-4 py-2 text-sm font-semibold">Rentabilidad</Link>{item.saleId?<Link href={`/admin/ventas/${item.saleId}`} className="rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-white">Ver venta</Link>:null}</div></div>{message?<p className="rounded-xl bg-green-50 p-3 text-sm text-green-700">{message}</p>:null}{error?<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}
<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Card label="Costo compra" value={item.acquisitionCostCop}/><Card label="Extras preventa" value={item.preSaleExtraCostsCop}/><Card label="Extras posventa" value={item.postSaleExtraCostsCop}/><Card label="Utilidad actual" value={item.currentProfitCop} highlight/></div>
<section className="rounded-2xl border border-border bg-white p-5"><h2 className="font-semibold text-text">Desglose del margen</h2><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><Row label="Ingreso bruto ítem" value={item.saleGrossRevenueCop}/><Row label="Descuento asignado" value={item.allocatedDiscountCop}/><Row label="Ingreso neto STU" value={item.netRevenueCop}/><Row label="Costos generales asignados" value={item.allocatedSaleCostsCop}/><Row label="Compra / adquisición" value={item.acquisitionCostCop}/><Row label="Extras del STU" value={item.totalUnitExtraCostsCop}/><Row label="Costo conocido total" value={item.totalKnownCostCop}/><Row label="Margen" text={item.marginPercent==null?"—":`${item.marginPercent}%`}/></div><p className="mt-4 text-xs text-muted">Origen: {item.purchaseNumber?`${item.purchaseNumber} · ${item.supplierName??"Proveedor"}`:"Recepción histórica/suelta"}. Estado de costeo: {item.costingStatus==="complete"?"Completo":item.costingStatus==="unsold"?"Aún no vendido":"Falta costo de adquisición"}.</p></section>
<section className="rounded-2xl border border-border bg-white p-5"><h2 className="font-semibold text-text">Agregar costo al STU</h2><div className="mt-3 grid gap-3 sm:grid-cols-3"><select value={category} onChange={e=>setCategory(e.target.value as CostCategory)} className="rounded-xl border border-border px-3 py-3 text-sm">{Object.entries(LABELS).filter(([k])=>!["sale_fee","accessory"].includes(k)).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><input value={description} onChange={e=>setDescription(e.target.value)} maxLength={500} placeholder="Ej. SSD 500 GB instalado" className="rounded-xl border border-border px-3 py-3 text-sm"/><input type="number" min={1} step={1000} value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Valor COP" className="rounded-xl border border-border px-3 py-3 text-sm"/></div><button disabled={working||description.trim().length<3||!amount} onClick={()=>void submit()} className="mt-3 rounded-xl bg-primary px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">{working?"Guardando...":"Registrar costo"}</button></section>
<section className="rounded-2xl border border-border bg-white p-5"><h2 className="font-semibold text-text">Ledger de costos</h2>{item.costEntries.length===0?<p className="mt-3 text-sm text-muted">Sin costos adicionales registrados.</p>:<div className="mt-3 space-y-2">{item.costEntries.map(c=><div key={c.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-surface p-3"><div><p className="font-mono text-xs font-bold text-primary">{c.costNumber}</p><p className="text-sm font-semibold text-text">{LABELS[c.category]} · {c.description}</p><p className="text-xs text-muted">{new Intl.DateTimeFormat("es-CO",{dateStyle:"medium"}).format(new Date(c.incurredAt))}{c.referenceType?` · ${c.referenceType}`:""}</p></div><div className="text-right"><p className={`font-bold ${c.amountCop<0?"text-green-700":"text-text"}`}>{c.amountCop<0?"−":""}{formatCOP(Math.abs(c.amountCop))}</p>{c.entryKind==="cost"&&!c.reversed?<button disabled={working} onClick={()=>void reverse(c.id)} className="mt-1 text-xs font-semibold text-red-600">Reversar</button>:<span className="mt-1 block text-xs text-muted">{c.entryKind==="reversal"?"Reverso":"Reversado"}</span>}</div></div>)}</div>}</section></div>}
function Card({label,value,highlight=false}:{label:string;value:number|null;highlight?:boolean}){return <div className="rounded-2xl border border-border bg-white p-4"><p className="text-xs font-semibold uppercase text-muted">{label}</p><p className={`mt-2 text-2xl font-bold ${highlight?"text-primary":"text-text"}`}>{value==null?"—":formatCOP(value)}</p></div>}
function Row({label,value,text}:{label:string;value?:number|null;text?:string}){return <div className="rounded-xl bg-surface p-3"><p className="text-[11px] text-muted">{label}</p><p className="mt-1 font-semibold text-text">{text??(value==null?"—":formatCOP(value))}</p></div>}
