"use server";
import type{SupabaseClient}from"@supabase/supabase-js";import{requireErpPermission}from"@/lib/erpAuth/auth";import type{AdminResult}from"@/lib/personalizadorAdmin/types";import{mapUnexpectedError}from"@/lib/personalizadorAdmin/errorMapping";import{closeCashSchema,cashMovementSchema,issues,openCashSchema,reverseMovementSchema}from"@/lib/adminPhase2/validation";import type{CashMovementDTO,CashSessionDTO}from"@/lib/adminPhase2/types";
async function run<T>(token:unknown,permission:"cash.read"|"cash.manage",fn:(c:SupabaseClient)=>Promise<AdminResult<T>>):Promise<AdminResult<T>>{try{const{client}=await requireErpPermission(token,permission);return await fn(client);}catch(e){return mapUnexpectedError(e);}}
const mapSession=(r:any):CashSessionDTO=>({id:r.id,sessionNumber:r.session_number,status:r.status,openingCashCop:Number(r.opening_cash_cop),expectedCashCop:r.expected_cash_cop==null?null:Number(r.expected_cash_cop),countedCashCop:r.counted_cash_cop==null?null:Number(r.counted_cash_cop),differenceCop:r.difference_cop==null?null:Number(r.difference_cop),openedAt:r.opened_at,closedAt:r.closed_at});
const mapMovement=(r:any):CashMovementDTO=>({id:r.id,movementNumber:r.movement_number,sessionId:r.session_id,movementType:r.movement_type,paymentMethod:r.payment_method,amountCop:Number(r.amount_cop),description:r.description,createdAt:r.created_at,reversalOfId:r.reversal_of_id});
export async function getCashDashboard(p:{accessToken:unknown}):Promise<AdminResult<{open:CashSessionDTO|null;sessions:CashSessionDTO[];movements:CashMovementDTO[]}>>{return run(p.accessToken,"cash.read",async c=>{const[s,m]=await Promise.all([c.from("cash_sessions").select("id,session_number,status,opening_cash_cop,expected_cash_cop,counted_cash_cop,difference_cop,opened_at,closed_at").order("opened_at",{ascending:false}).limit(30),c.from("cash_movements").select("id,movement_number,session_id,movement_type,payment_method,amount_cop,description,created_at,reversal_of_id").order("created_at",{ascending:false}).limit(100)]);if(s.error||m.error)throw s.error??m.error;const sessions=(s.data??[]).map(mapSession);return{ok:true,data:{open:sessions.find(x=>x.status==="open")??null,sessions,movements:(m.data??[]).map(mapMovement)}};});}
export async function openCash(p:{accessToken:unknown;openingCashCop:unknown;notes?:unknown}):Promise<AdminResult<{id:string}>>{const v=openCashSchema.safeParse({openingCashCop:p.openingCashCop,notes:p.notes});if(!v.success)return{ok:false,error:"VALIDATION_ERROR",issues:issues(v.error)};return run(p.accessToken,"cash.manage",async c=>{const{data,error}=await c.rpc("erp_open_cash_session",{p_opening_cash_cop:v.data.openingCashCop,p_notes:v.data.notes??null});if(error)throw error;return{ok:true,data:{id:String(data)}};});}
export async function closeCash(p:{accessToken:unknown;sessionId:unknown;countedCashCop:unknown;notes?:unknown}):Promise<AdminResult<{id:string}>>{const v=closeCashSchema.safeParse({sessionId:p.sessionId,countedCashCop:p.countedCashCop,notes:p.notes});if(!v.success)return{ok:false,error:"VALIDATION_ERROR",issues:issues(v.error)};return run(p.accessToken,"cash.manage",async c=>{const{data,error}=await c.rpc("erp_close_cash_session",{p_session_id:v.data.sessionId,p_counted_cash_cop:v.data.countedCashCop,p_notes:v.data.notes??null});if(error)throw error;return{ok:true,data:{id:String(data)}};});}
export async function addCashMovement(p:{accessToken:unknown;[k:string]:unknown}):Promise<AdminResult<{id:string}>>{const{accessToken,...input}=p;const v=cashMovementSchema.safeParse(input);if(!v.success)return{ok:false,error:"VALIDATION_ERROR",issues:issues(v.error)};return run(accessToken,"cash.manage",async c=>{const{data,error}=await c.rpc("erp_add_cash_movement",{p_movement_type:v.data.movementType,p_payment_method:v.data.paymentMethod,p_amount_cop:v.data.amountCop,p_description:v.data.description,p_purchase_id:v.data.purchaseId??null});if(error)throw error;return{ok:true,data:{id:String(data)}};});}
export async function reverseCashMovement(p:{accessToken:unknown;movementId:unknown;reason:unknown}):Promise<AdminResult<{id:string}>>{const v=reverseMovementSchema.safeParse({movementId:p.movementId,reason:p.reason});if(!v.success)return{ok:false,error:"VALIDATION_ERROR",issues:issues(v.error)};return run(p.accessToken,"cash.manage",async c=>{const{data,error}=await c.rpc("erp_reverse_cash_movement",{p_movement_id:v.data.movementId,p_reason:v.data.reason});if(error)throw error;return{ok:true,data:{id:String(data)}};});}
