"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { callAdminAction } from "@/lib/callAdminAction";
import { getAfterSalesCase, progressAfterSalesCase } from "@/app/admin/garantias/actions";
import { formatCOP } from "@/lib/personalizadorUi";
import type { AdminAfterSalesCaseDetailDTO, AfterSalesCaseAction, AfterSalesCaseStatus } from "@/lib/afterSalesAdmin/types";

const STATUS_LABELS:Record<AfterSalesCaseStatus,string>={open:"Abierto",diagnosing:"Diagnóstico",repair:"Reparación",waiting_customer:"Esperando cliente",closed:"Cerrado",cancelled:"Cancelado"};
const COVERAGE={in_warranty:"En garantía",out_of_warranty:"Fuera de garantía",not_applicable:"No aplica"} as const;
const EVENT_LABELS:Record<string,string>={opened:"Caso abierto",diagnosis_started:"Diagnóstico iniciado",sent_to_repair:"Enviado a reparación",waiting_customer:"Esperando cliente",closed_returned_to_customer:"Devuelto al cliente y cerrado",closed_retired:"Equipo retirado y caso cerrado",cancelled:"Caso cancelado"};
function dt(iso:string|null){if(!iso)return "—";return new Intl.DateTimeFormat("es-CO",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(iso));}

export default function CasoPosventaPage(){
  const {id}=useParams<{id:string}>(); const [item,setItem]=useState<AdminAfterSalesCaseDetailDTO|null>(null); const [loading,setLoading]=useState(true); const [working,setWorking]=useState(false); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [diagnosis,setDiagnosis]=useState(""); const [note,setNote]=useState(""); const [cost,setCost]=useState("");
  const load=useCallback(async()=>{try{setLoading(true);const r=await callAdminAction(getAfterSalesCase,{caseId:id});if(!r.ok){setError(r.error==="NOT_FOUND"?"Caso no encontrado.":"No fue posible cargar el caso.");return;}setItem(r.data);setDiagnosis(r.data.diagnosis??"");}catch{setError("No fue posible cargar el caso.");}finally{setLoading(false);}},[id]);
  useEffect(()=>{void load();},[load]);
  const run=async(action:AfterSalesCaseAction)=>{if(working)return;try{setWorking(true);setError("");setMessage("");const n=note.trim()||undefined;const d=diagnosis.trim()||undefined;const c=cost.trim()===""?undefined:Number(cost);const r=await callAdminAction(progressAfterSalesCase,{caseId:id,action,note:n,diagnosis:d,costCop:c});if(!r.ok){setError(r.error==="VALIDATION_ERROR"?r.issues.join(" "):"No fue posible actualizar el caso.");return;}setItem(r.data);setDiagnosis(r.data.diagnosis??"");setNote("");setCost("");setMessage("Caso actualizado correctamente.");}catch{setError("No fue posible actualizar el caso.");}finally{setWorking(false);}};
  if(loading)return <p className="text-sm text-muted">Cargando caso...</p>; if(!item)return <div className="space-y-3"><p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error||"Caso no encontrado."}</p><Link href="/admin/garantias" className="text-sm font-semibold text-primary">← Volver</Link></div>;
  const terminal=item.status==="closed"||item.status==="cancelled";
  const canRepair=!terminal&&["warranty","returned"].includes(item.unitStatus)&&["open","diagnosing","waiting_customer"].includes(item.status);
  const canReturn=!terminal&&((item.caseType==="warranty"&&["warranty","repair"].includes(item.unitStatus))||(item.caseType==="return"&&["returned","repair"].includes(item.unitStatus)));
  const canRetire=!terminal&&["warranty","returned","repair"].includes(item.unitStatus);
  const canCancel=!terminal&&["open","diagnosing","waiting_customer"].includes(item.status)&&["warranty","returned"].includes(item.unitStatus);
  return <div className="space-y-6">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-widest text-primary">ERP · {item.caseType==="warranty"?"Garantía":"Devolución"}</p><h1 className="font-mono text-2xl font-bold text-text">{item.caseNumber}</h1><p className="mt-1 text-sm text-muted">Venta {item.saleNumber} · {item.unitCode} · Serial {item.serialNumber??"sin registrar"}</p></div><div className="flex gap-2"><Link href="/admin/garantias" className="rounded-xl border border-border px-4 py-2.5 text-sm font-semibold text-text">Volver</Link><Link href={`/admin/ventas/${item.saleId}`} className="rounded-xl border border-border px-4 py-2.5 text-sm font-semibold text-text">Ver venta</Link></div></div>
    {message?<p className="rounded-xl border border-green-100 bg-green-50 px-4 py-3 text-sm text-green-700">{message}</p>:null}{error?<p className="rounded-xl border border-red-100 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>:null}
    <div className="grid gap-4 lg:grid-cols-3"><section className="rounded-2xl border border-border bg-white p-5 lg:col-span-2"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-lg font-semibold text-text">Expediente</h2><div className="flex gap-2"><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">{STATUS_LABELS[item.status]}</span><span className="rounded-full bg-surface px-3 py-1 text-xs font-semibold text-muted">Unidad: {item.unitStatus}</span></div></div><div className="mt-4 grid gap-2 text-sm sm:grid-cols-2"><p><span className="text-muted">Cliente:</span> {item.customerName}</p><p><span className="text-muted">Documento:</span> {item.customerDocument}</p><p><span className="text-muted">Celular:</span> {item.customerPhone}</p><p><span className="text-muted">Cobertura:</span> {COVERAGE[item.coverageStatus]}</p><p><span className="text-muted">Garantía vence:</span> {dt(item.warrantyExpiresAt)}</p><p><span className="text-muted">Abierto:</span> {dt(item.openedAt)}</p></div><div className="mt-4 space-y-3"><div className="rounded-xl bg-surface p-3 text-sm"><p className="text-xs font-semibold uppercase text-muted">Motivo reportado</p><p className="mt-1 text-text">{item.reportedIssue}</p></div>{item.intakeCondition?<div className="rounded-xl bg-surface p-3 text-sm"><p className="text-xs font-semibold uppercase text-muted">Estado al recibir</p><p className="mt-1 text-text">{item.intakeCondition}</p></div>:null}{item.diagnosis?<div className="rounded-xl bg-amber-50 p-3 text-sm"><p className="text-xs font-semibold uppercase text-amber-700">Diagnóstico</p><p className="mt-1 text-text">{item.diagnosis}</p></div>:null}{item.resolution?<div className="rounded-xl bg-green-50 p-3 text-sm"><p className="text-xs font-semibold uppercase text-green-700">Resolución</p><p className="mt-1 text-text">{item.resolution}</p></div>:null}</div></section>
      <section className="rounded-2xl border border-border bg-white p-5"><h2 className="font-semibold text-text">Costos y evidencias</h2><div className="mt-3 space-y-2 text-sm"><p><span className="text-muted">Estimado:</span> {item.estimatedCostCop==null?"—":formatCOP(item.estimatedCostCop)}</p><p><span className="text-muted">Final:</span> {item.finalCostCop==null?"—":formatCOP(item.finalCostCop)}</p><p><span className="text-muted">Evidencias:</span> {item.evidenceUrls.length}</p></div>{item.evidenceUrls.length?<div className="mt-3 space-y-1">{item.evidenceUrls.map((u,i)=><a key={u+i} href={u} target="_blank" rel="noreferrer" className="block truncate text-xs font-medium text-primary hover:underline">Evidencia {i+1}</a>)}</div>:null}</section></div>
    {!terminal?<section className="space-y-4 rounded-2xl border border-border bg-white p-5"><div><h2 className="text-lg font-semibold text-text">Actualizar caso</h2><p className="text-xs text-muted">Las transiciones que afectan el equipo se registran también en Inventario y Auditoría.</p></div><label className="block"><span className="mb-1 block text-sm font-medium text-text">Diagnóstico</span><textarea value={diagnosis} onChange={e=>setDiagnosis(e.target.value)} rows={3} maxLength={4000} className="w-full rounded-xl border border-border px-4 py-3 text-sm"/></label><div className="grid gap-3 sm:grid-cols-2"><label><span className="mb-1 block text-sm font-medium text-text">Nota / resolución</span><textarea value={note} onChange={e=>setNote(e.target.value)} rows={3} maxLength={4000} className="w-full rounded-xl border border-border px-4 py-3 text-sm"/></label><label><span className="mb-1 block text-sm font-medium text-text">Costo COP</span><input type="number" min={0} step={1000} value={cost} onChange={e=>setCost(e.target.value)} className="w-full rounded-xl border border-border px-4 py-3 text-sm" placeholder="Opcional"/></label></div><div className="flex flex-wrap gap-2"><button disabled={working||item.status==="diagnosing"} onClick={()=>void run("start_diagnosis")} className="rounded-xl border border-border px-4 py-2.5 text-sm font-semibold text-text disabled:opacity-40">Iniciar diagnóstico</button>{canRepair?<button disabled={working} onClick={()=>void run("send_repair")} className="rounded-xl bg-amber-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Enviar a reparación</button>:null}<button disabled={working||item.status==="waiting_customer"} onClick={()=>void run("waiting_customer")} className="rounded-xl border border-violet-200 px-4 py-2.5 text-sm font-semibold text-violet-700 disabled:opacity-40">Esperando cliente</button>{canReturn?<button disabled={working} onClick={()=>void run("close_returned")} className="rounded-xl bg-green-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Cerrar y devolver al cliente</button>:null}{canRetire?<button disabled={working} onClick={()=>void run("close_retired")} className="rounded-xl bg-slate-800 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Cerrar y retirar equipo</button>:null}{canCancel?<button disabled={working} onClick={()=>void run("cancel")} className="rounded-xl border border-red-200 px-4 py-2.5 text-sm font-semibold text-red-700 disabled:opacity-40">Cancelar caso</button>:null}</div></section>:null}
    <section className="rounded-2xl border border-border bg-white p-5"><h2 className="text-lg font-semibold text-text">Línea de tiempo</h2><div className="mt-4 space-y-3">{item.events.map(ev=><div key={ev.id} className="border-l-2 border-border pl-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-semibold text-text">{EVENT_LABELS[ev.eventType]??ev.eventType}</p><p className="text-xs text-muted">{dt(ev.createdAt)}</p></div>{ev.note?<p className="mt-1 text-sm text-muted">{ev.note}</p>:null}{ev.costCop!=null?<p className="mt-1 text-xs font-medium text-primary">Costo: {formatCOP(ev.costCop)}</p>:null}</div>)}</div></section>
  </div>;
}
