"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { callAdminAction } from "@/lib/callAdminAction";
import { listPurchaseSuppliers, receivePurchaseBatch, searchPurchaseProducts } from "@/app/admin/compras/actions";
import { formatCOP } from "@/lib/personalizadorUi";
import { allocateSharedCosts } from "@/lib/purchaseAdmin/costs";
import type { AdminPurchaseProductDTO, AdminSupplierDTO } from "@/lib/purchaseAdmin/types";

interface LocalUnit { localId:string; product:AdminPurchaseProductDTO; serialNumber:string; baseCost:string; batteryHealth:string; storageHealth:string; ramGb:string; storageGb:string; storageType:string; conditionNotes:string; notes:string; }
const uid=()=>typeof crypto!=="undefined"&&"randomUUID" in crypto?crypto.randomUUID():String(Math.random());
function bogotaToday(){return new Intl.DateTimeFormat("en-CA",{timeZone:"America/Bogota",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());}

export default function NuevaCompraPage(){
  const router=useRouter();
  const [suppliers,setSuppliers]=useState<AdminSupplierDTO[]>([]);const [supplierId,setSupplierId]=useState("");const [invoiceRef,setInvoiceRef]=useState("");const [purchaseDate,setPurchaseDate]=useState(bogotaToday);const [sharedCosts,setSharedCosts]=useState("0");const [notes,setNotes]=useState("");
  const [units,setUnits]=useState<LocalUnit[]>([]);const [query,setQuery]=useState("");const [results,setResults]=useState<AdminPurchaseProductDTO[]>([]);const [searching,setSearching]=useState(false);const [loading,setLoading]=useState(true);const [submitting,setSubmitting]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{let cancelled=false;(async()=>{try{const r=await callAdminAction(listPurchaseSuppliers,{query:""});if(cancelled)return;if(r.ok){setSuppliers(r.data.items);if(r.data.items.length)setSupplierId(r.data.items[0].id);}else setError("No fue posible cargar proveedores.");}catch{if(!cancelled)setError("No fue posible cargar proveedores.");}finally{if(!cancelled)setLoading(false);}})();return()=>{cancelled=true};},[]);
  const search=async(e:React.FormEvent)=>{e.preventDefault();if(!query.trim())return;try{setSearching(true);setError("");const r=await callAdminAction(searchPurchaseProducts,{query:query.trim()});setResults(r.ok?r.data.items:[]);}catch{setError("No fue posible buscar productos.");}finally{setSearching(false);}};
  const add=(product:AdminPurchaseProductDTO)=>{setUnits(prev=>[...prev,{localId:uid(),product,serialNumber:"",baseCost:"",batteryHealth:"",storageHealth:"",ramGb:"",storageGb:"",storageType:"SSD",conditionNotes:"",notes:""}]);setResults([]);setQuery("");};
  const patch=(id:string,p:Partial<LocalUnit>)=>setUnits(prev=>prev.map(u=>u.localId===id?{...u,...p}:u));
  const remove=(id:string)=>setUnits(prev=>prev.filter(u=>u.localId!==id));
  const subtotal=useMemo(()=>units.reduce((s,u)=>s+(Number(u.baseCost)||0),0),[units]);
  const shared=Math.max(0,Number(sharedCosts)||0); const total=subtotal+shared;
  const allocations=units.length>0&&Number.isInteger(shared)?allocateSharedCosts(shared,units.length):Array.from({length:units.length},()=>0);
  const duplicateSerial=useMemo(()=>{const seen=new Set<string>();for(const u of units){const s=u.serialNumber.trim().toLowerCase();if(!s)continue;if(seen.has(s))return true;seen.add(s);}return false;},[units]);
  const canSubmit=Boolean(supplierId&&purchaseDate&&units.length>0&&!duplicateSerial&&Number.isInteger(shared)&&shared>=0&&units.every(u=>u.baseCost.trim()!==""&&Number.isInteger(Number(u.baseCost))&&Number(u.baseCost)>=0));
  const submit=async()=>{if(!canSubmit||submitting)return;try{setSubmitting(true);setError("");const r=await callAdminAction(receivePurchaseBatch,{supplierId,supplierInvoiceReference:invoiceRef.trim()||undefined,purchaseDate,sharedCostsCop:shared,notes:notes.trim()||undefined,units:units.map(u=>({productId:u.product.id,serialNumber:u.serialNumber.trim()||undefined,baseCostCop:Number(u.baseCost),batteryHealthPercent:u.batteryHealth.trim()===""?undefined:Number(u.batteryHealth),storageHealthPercent:u.storageHealth.trim()===""?undefined:Number(u.storageHealth),ramGb:u.ramGb.trim()===""?undefined:Number(u.ramGb),storageGb:u.storageGb.trim()===""?undefined:Number(u.storageGb),storageType:u.storageGb.trim()===""?undefined:u.storageType.trim()||undefined,conditionNotes:u.conditionNotes.trim()||undefined,notes:u.notes.trim()||undefined}))});if(!r.ok){setError(r.error==="VALIDATION_ERROR"?r.issues.join(" "):"No fue posible recibir la compra.");return;}router.push(`/admin/compras/${r.data.id}`);}catch{setError("No fue posible recibir la compra.");}finally{setSubmitting(false);}};
  if(loading)return <p className="text-sm text-muted">Cargando...</p>;
  return <div className="space-y-6 pb-28"><div><p className="text-xs font-semibold uppercase tracking-widest text-primary">ERP · Fase 1G</p><h1 className="text-2xl font-bold text-text">Recibir compra por lote</h1><p className="mt-1 text-sm text-muted">Una confirmación crea COMP + todos los STU + movimientos + auditoría. Si una unidad falla, no se guarda ninguna.</p></div>
    {error?<p className="rounded-xl border border-red-100 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>:null}{duplicateSerial?<p className="rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-800">Hay un serial repetido dentro del lote.</p>:null}
    <section className="space-y-4 rounded-2xl border border-border bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-semibold text-text">Compra</h2><Link href="/admin/proveedores" className="text-xs font-semibold text-primary">Administrar proveedores</Link></div>{suppliers.length===0?<p className="rounded-xl bg-amber-50 p-3 text-sm text-amber-800">Primero registra un proveedor.</p>:<div className="grid gap-3 sm:grid-cols-2"><label className="text-sm"><span className="mb-1 block font-medium">Proveedor *</span><select value={supplierId} onChange={e=>setSupplierId(e.target.value)} className="w-full rounded-xl border border-border bg-white px-4 py-3">{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}{s.documentNumber?` · ${s.documentNumber}`:""}</option>)}</select></label><label className="text-sm"><span className="mb-1 block font-medium">Fecha *</span><input type="date" value={purchaseDate} onChange={e=>setPurchaseDate(e.target.value)} className="w-full rounded-xl border border-border px-4 py-3"/></label><label className="text-sm"><span className="mb-1 block font-medium">Factura / comprobante proveedor</span><input value={invoiceRef} onChange={e=>setInvoiceRef(e.target.value)} maxLength={120} className="w-full rounded-xl border border-border px-4 py-3"/></label><label className="text-sm"><span className="mb-1 block font-medium">Flete / otros costos compartidos</span><input type="number" min={0} step={1000} value={sharedCosts} onChange={e=>setSharedCosts(e.target.value)} className="w-full rounded-xl border border-border px-4 py-3"/></label></div>}<label className="block text-sm"><span className="mb-1 block font-medium">Notas del lote</span><textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={2} className="w-full rounded-xl border border-border px-4 py-3"/></label></section>
    <section className="space-y-4 rounded-2xl border border-border bg-white p-5"><div><h2 className="font-semibold text-text">Computadores del lote</h2><p className="text-xs text-muted">Agrega una fila por máquina física, incluso cuando sean del mismo modelo.</p></div><form onSubmit={search} className="flex gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar modelo para agregar" className="flex-1 rounded-xl border border-border px-4 py-3 text-sm"/><button disabled={searching} className="rounded-xl border border-primary px-5 py-3 text-sm font-semibold text-primary">{searching?"...":"Buscar"}</button></form>{results.length>0?<div className="grid gap-2 sm:grid-cols-2">{results.map(p=><button type="button" key={p.id} onClick={()=>add(p)} className="rounded-xl border border-border p-3 text-left hover:border-primary"><p className="font-semibold text-text">{p.title}</p><p className="text-xs text-muted">{p.cpu} · {p.ram} GB RAM · {p.storage}</p></button>)}</div>:null}
      {units.length===0?<p className="rounded-xl border border-dashed border-border p-6 text-center text-sm text-muted">No has agregado computadores.</p>:<div className="space-y-3">{units.map((u,i)=>{const alloc=allocations[i]??0;const landed=(Number(u.baseCost)||0)+alloc;return <article key={u.localId} className="rounded-xl border border-border p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-primary">Unidad {i+1}</p><h3 className="font-semibold text-text">{u.product.title}</h3><p className="text-xs text-muted">{u.product.brand} {u.product.model}</p></div><button type="button" onClick={()=>remove(u.localId)} className="text-xs font-semibold text-red-600">Eliminar</button></div><div className="mt-3 grid gap-2 sm:grid-cols-4"><label className="text-xs sm:col-span-2">Serial<input value={u.serialNumber} onChange={e=>patch(u.localId,{serialNumber:e.target.value})} className="mt-1 w-full rounded-lg border border-border px-3 py-2 text-sm"/></label><label className="text-xs">Costo compra *<input type="number" min={0} step={1000} value={u.baseCost} onChange={e=>patch(u.localId,{baseCost:e.target.value})} className="mt-1 w-full rounded-lg border border-border px-3 py-2 text-sm"/></label><div className="rounded-lg bg-green-50 p-2 text-xs"><p className="text-green-700">Costo real STU</p><p className="mt-1 font-bold text-green-800">{formatCOP(landed)}</p><p className="text-[10px] text-green-700">+ {formatCOP(alloc)} lote</p></div><label className="text-xs">Batería %<input type="number" min={0} max={100} value={u.batteryHealth} onChange={e=>patch(u.localId,{batteryHealth:e.target.value})} className="mt-1 w-full rounded-lg border border-border px-3 py-2 text-sm"/></label><label className="text-xs">Disco %<input type="number" min={0} max={100} value={u.storageHealth} onChange={e=>patch(u.localId,{storageHealth:e.target.value})} className="mt-1 w-full rounded-lg border border-border px-3 py-2 text-sm"/></label><label className="text-xs">RAM real GB<input type="number" min={1} value={u.ramGb} onChange={e=>patch(u.localId,{ramGb:e.target.value})} className="mt-1 w-full rounded-lg border border-border px-3 py-2 text-sm"/></label><label className="text-xs">Almacenamiento real GB<input type="number" min={1} value={u.storageGb} onChange={e=>patch(u.localId,{storageGb:e.target.value})} className="mt-1 w-full rounded-lg border border-border px-3 py-2 text-sm"/></label><label className="text-xs">Tipo disco<input value={u.storageType} onChange={e=>patch(u.localId,{storageType:e.target.value})} className="mt-1 w-full rounded-lg border border-border px-3 py-2 text-sm"/></label><label className="text-xs sm:col-span-3">Condición / notas unidad<input value={u.conditionNotes} onChange={e=>patch(u.localId,{conditionNotes:e.target.value})} className="mt-1 w-full rounded-lg border border-border px-3 py-2 text-sm"/></label></div></article>;})}</div>}
    </section>
    <section className="rounded-2xl border border-border bg-surface p-5"><h2 className="font-semibold text-text">Cuadre del lote</h2><div className="mt-3 space-y-2 text-sm"><div className="flex justify-between"><span className="text-muted">{units.length} computador(es)</span><span>{formatCOP(subtotal)}</span></div><div className="flex justify-between"><span className="text-muted">Flete / otros costos</span><span>{formatCOP(shared)}</span></div><div className="flex justify-between border-t border-border pt-2 text-lg font-bold"><span>Total compra</span><span className="text-primary">{formatCOP(total)}</span></div></div><p className="mt-2 text-xs text-muted">Los gastos comunes se asignan a los STU en pesos enteros. La suma de costos reales siempre será exactamente igual al total de la compra.</p></section>
    <div className="fixed inset-x-0 bottom-0 z-10 border-t border-border bg-white/95 p-4 backdrop-blur"><div className="mx-auto flex max-w-4xl items-center justify-between gap-4"><div><p className="text-xs text-muted">Total a registrar</p><p className="text-xl font-bold text-text">{formatCOP(total)}</p></div><button onClick={()=>void submit()} disabled={!canSubmit||submitting} className="rounded-xl bg-primary px-6 py-3.5 text-sm font-semibold text-white disabled:opacity-40">{submitting?"Recibiendo lote...":"Confirmar y crear STU"}</button></div></div>
  </div>;
}
