"use client";
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
import {callAdminAction} from "@/lib/callAdminAction";
import {addCostEntry,listProfitability} from "@/app/admin/rentabilidad/actions";
import {formatCOP} from "@/lib/personalizadorUi";
import type {AdminProfitabilityDashboardDTO,AdminProfitabilitySaleDTO,CostCategory} from "@/lib/profitabilityAdmin/types";
const EMPTY:AdminProfitabilityDashboardDTO={summary:{saleCount:0,completeSaleCount:0,reviewSaleCount:0,revenueCop:0,knownCostCop:0,knownProfitCop:0,completeRevenueCop:0,completeCostCop:0,completeProfitCop:0},sales:[]};
const STATUS={complete:"Costeo completo",missing_acquisition_cost:"Falta costo de compra",manual_items_review:"Revisar ítems manuales"} as const;
export default function RentabilidadPage(){const[data,setData]=useState(EMPTY);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[message,setMessage]=useState("");const[working,setWorking]=useState<string|null>(null);const load=useCallback(async()=>{try{setLoading(true);setError("");const r=await callAdminAction(listProfitability,{limit:150});if(!r.ok){setError("No fue posible calcular la rentabilidad.");return;}setData(r.data);}catch{setError("No fue posible calcular la rentabilidad.");}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);
const addSaleCost=async(sale:AdminProfitabilitySaleDTO)=>{if(working)return;const raw=window.prompt("Categoría: transport | sale_fee | accessory | other","transport")?.trim() as CostCategory|undefined;if(!raw||!["transport","sale_fee","accessory","other"].includes(raw))return setError("Categoría inválida.");const desc=window.prompt(`Descripción del costo para ${sale.saleNumber}:`)?.trim();if(!desc)return;const amount=Number(window.prompt("Valor COP (entero):")?.trim());if(!Number.isInteger(amount)||amount<=0)return setError("Valor inválido.");try{setWorking(sale.saleId);setError("");setMessage("");const r=await callAdminAction(addCostEntry,{scopeType:"sale",scopeId:sale.saleId,category:raw,description:desc,amountCop:amount});if(!r.ok){setError(r.error==="VALIDATION_ERROR"?r.issues.join(" "):"No fue posible registrar el costo.");return;}setMessage(`Costo registrado en ${sale.saleNumber}.`);await load();}catch{setError("No fue posible registrar el costo.");}finally{setWorking(null);}};
const s=data.summary;return <div className="space-y-6"><div><p className="text-xs font-semibold uppercase tracking-widest text-primary">ERP · Fase 1H</p><h1 className="text-2xl font-bold text-text">Rentabilidad y costos reales</h1><p className="mt-1 text-sm text-muted">Compra + costos por STU + costos de venta + posventa. Las ventas incompletas se marcan; no se presentan como utilidad real cerrada.</p></div>{message?<p className="rounded-xl bg-green-50 p-3 text-sm text-green-700">{message}</p>:null}{error?<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}
<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Card label="Ventas analizadas" value={String(s.saleCount)} sub={`${s.completeSaleCount} completas · ${s.reviewSaleCount} por revisar`}/><Card label="Ingresos" value={formatCOP(s.revenueCop)} sub="Total facturado"/><Card label="Margen conocido" value={formatCOP(s.knownProfitCop)} sub={`Costos registrados: ${formatCOP(s.knownCostCop)}`}/><Card label="Utilidad costeo completo" value={formatCOP(s.completeProfitCop)} sub={`Sobre ${formatCOP(s.completeRevenueCop)} de ingresos completos`}/></div>
{loading?<p className="text-sm text-muted">Calculando...</p>:null}<div className="space-y-3">{data.sales.map(x=><article key={x.saleId} className="rounded-2xl border border-border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><Link href={`/admin/ventas/${x.saleId}`} className="font-mono text-sm font-bold text-primary hover:underline">{x.saleNumber}</Link><p className="mt-1 text-sm font-semibold text-text">{x.customerName}</p><p className="text-xs text-muted">{x.physicalItemCount} STU · {x.manualItemCount} ítem(s) manual(es)</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${x.costingStatus==="complete"?"bg-green-50 text-green-700":"bg-amber-50 text-amber-800"}`}>{STATUS[x.costingStatus]}</span></div><div className="mt-4 grid gap-2 sm:grid-cols-5"><Mini label="Ingreso" value={x.revenueCop}/><Mini label="Compra" value={x.acquisitionCostCop}/><Mini label="Extras STU" value={x.unitExtraCostsCop}/><Mini label="Costos venta" value={x.saleCostsCop}/><Mini label="Margen conocido" value={x.knownProfitCop} strong/></div><div className="mt-3 flex items-center justify-between gap-3"><p className="text-xs text-muted">Margen: {x.marginPercent==null?"—":`${x.marginPercent}%`}</p><button onClick={()=>void addSaleCost(x)} disabled={working!==null} className="rounded-xl border border-border px-3 py-2 text-xs font-semibold text-text hover:border-primary disabled:opacity-50">{working===x.saleId?"Registrando...":"+ Costo de venta"}</button></div></article>)}</div></div>}
function Card({label,value,sub}:{label:string;value:string;sub:string}){return <div className="rounded-2xl border border-border bg-white p-4"><p className="text-xs font-semibold uppercase text-muted">{label}</p><p className="mt-2 text-2xl font-bold text-text">{value}</p><p className="mt-1 text-xs text-muted">{sub}</p></div>}
function Mini({label,value,strong=false}:{label:string;value:number;strong?:boolean}){return <div className="rounded-xl bg-surface p-3"><p className="text-[11px] text-muted">{label}</p><p className={`mt-1 text-sm ${strong?"font-bold text-primary":"font-semibold text-text"}`}>{formatCOP(value)}</p></div>}
