"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { callAdminAction } from "@/lib/callAdminAction";
import { getPurchase } from "@/app/admin/compras/actions";
import { formatCOP } from "@/lib/personalizadorUi";
import type { AdminPurchaseDetailDTO } from "@/lib/purchaseAdmin/types";

export default function CompraDetallePage(){
  const {id}=useParams<{id:string}>();const [item,setItem]=useState<AdminPurchaseDetailDTO|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  useEffect(()=>{let cancelled=false;(async()=>{try{const r=await callAdminAction(getPurchase,{purchaseId:id});if(cancelled)return;if(!r.ok){setError(r.error==="NOT_FOUND"?"Compra no encontrada.":"No fue posible cargar la compra.");return;}setItem(r.data);}catch{if(!cancelled)setError("No fue posible cargar la compra.");}finally{if(!cancelled)setLoading(false);}})();return()=>{cancelled=true};},[id]);
  if(loading)return <p className="text-sm text-muted">Cargando compra...</p>;if(!item)return <div className="space-y-3"><p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error||"Compra no encontrada."}</p><Link href="/admin/compras" className="text-sm font-semibold text-primary">← Volver</Link></div>;
  const sumLanded=item.items.reduce((s,x)=>s+x.landedCostCop,0);
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-widest text-primary">ERP · Compra recibida</p><h1 className="font-mono text-2xl font-bold text-text">{item.purchaseNumber}</h1><p className="mt-1 text-sm text-muted">{item.purchaseDate} · {item.supplierName}</p></div><div className="flex gap-2"><Link href="/admin/compras" className="rounded-xl border border-border px-4 py-2.5 text-sm font-semibold">Volver</Link><Link href="/admin/inventario" className="rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-white">Ver inventario</Link></div></div>
    <section className="rounded-2xl border border-border bg-white p-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs text-muted">Proveedor</p><p className="font-semibold text-text">{item.supplierName}</p><p className="text-xs text-muted">{item.supplierDocument??"Sin documento"}</p></div><div><p className="text-xs text-muted">Factura / referencia</p><p className="font-semibold text-text">{item.supplierInvoiceReference??"—"}</p></div><div><p className="text-xs text-muted">Celular proveedor</p><p className="font-semibold text-text">{item.supplierPhone??"—"}</p></div><div><p className="text-xs text-muted">Estado</p><span className="mt-1 inline-block rounded-full bg-green-50 px-2.5 py-1 text-xs font-semibold text-green-700">Recibida</span></div></div>{item.notes?<p className="mt-4 rounded-xl bg-surface p-3 text-sm text-muted">{item.notes}</p>:null}</section>
    <section className="space-y-3 rounded-2xl border border-border bg-white p-5"><div><h2 className="text-lg font-semibold text-text">Computadores recibidos</h2><p className="text-xs text-muted">Cada línea corresponde a un STU físico y conserva su costo histórico.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-border text-xs text-muted"><th className="py-2 pr-3">STU / Serial</th><th className="py-2 pr-3">Producto</th><th className="py-2 pr-3 text-right">Compra</th><th className="py-2 pr-3 text-right">Gasto asignado</th><th className="py-2 text-right">Costo real STU</th></tr></thead><tbody>{item.items.map(x=><tr key={x.id} className="border-b border-border/70"><td className="py-3 pr-3"><p className="font-mono font-bold text-primary">{x.unitCode}</p><p className="text-xs text-muted">{x.serialNumber??"Sin serial"}</p></td><td className="py-3 pr-3"><p className="font-medium text-text">{x.productName}</p>{x.notes?<p className="text-xs text-muted">{x.notes}</p>:null}</td><td className="py-3 pr-3 text-right">{formatCOP(x.baseCostCop)}</td><td className="py-3 pr-3 text-right">{formatCOP(x.allocatedExtraCostCop)}</td><td className="py-3 text-right font-bold text-green-700">{formatCOP(x.landedCostCop)}</td></tr>)}</tbody></table></div></section>
    <section className="rounded-2xl border border-border bg-surface p-5"><h2 className="font-semibold text-text">Cuadre contable del lote</h2><div className="mt-3 ml-auto max-w-md space-y-2 text-sm"><div className="flex justify-between"><span className="text-muted">Mercancía</span><span>{formatCOP(item.merchandiseSubtotalCop)}</span></div><div className="flex justify-between"><span className="text-muted">Flete / otros</span><span>{formatCOP(item.sharedCostsCop)}</span></div><div className="flex justify-between border-t border-border pt-2 text-lg font-bold"><span>Total COMP</span><span>{formatCOP(item.totalCostCop)}</span></div><div className={`flex justify-between rounded-lg px-3 py-2 ${sumLanded===item.totalCostCop?"bg-green-50 text-green-700":"bg-red-50 text-red-700"}`}><span>Suma costos STU</span><span className="font-bold">{formatCOP(sumLanded)}</span></div></div></section>
  </div>;
}
