"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { callAdminAction } from "@/lib/callAdminAction";
import { getAfterSalesOrigin, openAfterSalesCase } from "@/app/admin/garantias/actions";
import type { AdminAfterSalesOriginDTO, AfterSalesCaseType } from "@/lib/afterSalesAdmin/types";

function fmt(iso:string|null){if(!iso)return "—";return new Intl.DateTimeFormat("es-CO",{day:"2-digit",month:"long",year:"numeric"}).format(new Date(iso));}

export default function NuevaGarantiaPage(){
  const router=useRouter(); const [saleItemId,setSaleItemId]=useState("");
  const [origin,setOrigin]=useState<AdminAfterSalesOriginDTO|null>(null); const [caseType,setCaseType]=useState<AfterSalesCaseType>("warranty"); const [reportedIssue,setReportedIssue]=useState(""); const [intakeCondition,setIntakeCondition]=useState(""); const [evidenceText,setEvidenceText]=useState(""); const [loading,setLoading]=useState(true); const [submitting,setSubmitting]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{let cancelled=false;(async()=>{const id=new URLSearchParams(window.location.search).get("saleItemId")??"";setSaleItemId(id);if(!id){setError("Falta seleccionar un computador vendido.");setLoading(false);return;}try{const r=await callAdminAction(getAfterSalesOrigin,{saleItemId:id});if(cancelled)return;if(!r.ok){setError("No fue posible cargar el equipo de la venta.");return;}setOrigin(r.data);}catch{if(!cancelled)setError("No fue posible cargar el equipo de la venta.");}finally{if(!cancelled)setLoading(false);}})();return()=>{cancelled=true};},[]);
  const evidenceUrls=useMemo(()=>evidenceText.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),[evidenceText]);
  const canOpen=Boolean(origin&&origin.unitStatus==="sold"&&!origin.hasOpenCase&&reportedIssue.trim().length>=3&&evidenceUrls.length<=12);
  const submit=async()=>{if(!canOpen||submitting||!saleItemId)return;try{setSubmitting(true);setError("");const r=await callAdminAction(openAfterSalesCase,{saleItemId,caseType,reportedIssue,intakeCondition:intakeCondition.trim()||undefined,evidenceUrls});if(!r.ok){setError(r.error==="VALIDATION_ERROR"?r.issues.join(" "):"No fue posible abrir el caso.");return;}router.push(`/admin/garantias/${r.data.id}`);}catch{setError("No fue posible abrir el caso.");}finally{setSubmitting(false);}};
  if(loading)return <p className="text-sm text-muted">Cargando venta...</p>;
  if(error&&!origin)return <div className="space-y-4"><p className="rounded-xl border border-red-100 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p><Link href="/admin/ventas" className="text-sm font-semibold text-primary">← Volver a ventas</Link></div>;
  if(!origin)return null;
  const inWarranty=origin.warrantyExpiresAt?new Date(origin.warrantyExpiresAt)>=new Date():false;
  return <div className="mx-auto max-w-3xl space-y-6">
    <div><p className="text-xs font-semibold uppercase tracking-widest text-primary">ERP · Posventa</p><h1 className="text-2xl font-bold text-text">Abrir caso posventa</h1><p className="mt-1 text-sm text-muted">El expediente quedará ligado permanentemente a esta venta y unidad física.</p></div>
    {error?<p className="rounded-xl border border-red-100 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>:null}
    <section className="rounded-2xl border border-border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-sm font-bold text-primary">{origin.unitCode}</p><h2 className="text-lg font-semibold text-text">{origin.productName}</h2><p className="text-sm text-muted">Serial {origin.serialNumber??"sin registrar"}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-700">{origin.unitStatus}</span></div><div className="mt-4 grid gap-2 text-sm sm:grid-cols-2"><p><span className="text-muted">Venta:</span> {origin.saleNumber}</p><p><span className="text-muted">Fecha:</span> {fmt(origin.saleCreatedAt)}</p><p><span className="text-muted">Cliente:</span> {origin.customerName}</p><p><span className="text-muted">Celular:</span> {origin.customerPhone}</p><p><span className="text-muted">Garantía:</span> {origin.warrantyMonths} meses</p><p><span className="text-muted">Vence:</span> {fmt(origin.warrantyExpiresAt)}</p></div>{origin.warrantyMonths>0?<p className={`mt-3 rounded-xl px-3 py-2 text-sm font-medium ${inWarranty?"bg-green-50 text-green-700":"bg-amber-50 text-amber-800"}`}>{inWarranty?"La venta está dentro del período de garantía registrado.":"El período de garantía registrado ya venció. El caso se guardará como Fuera de garantía."}</p>:null}{origin.hasOpenCase?<p className="mt-3 rounded-xl bg-red-50 px-3 py-2 text-sm text-red-700">Esta unidad ya tiene un caso posventa abierto.</p>:null}{origin.unitStatus!=="sold"?<p className="mt-3 rounded-xl bg-amber-50 px-3 py-2 text-sm text-amber-800">Solo se puede abrir un caso nuevo cuando la unidad está actualmente en estado Vendido.</p>:null}</section>
    <section className="space-y-4 rounded-2xl border border-border bg-white p-5"><div><p className="text-sm font-semibold text-text">Tipo de caso</p><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" onClick={()=>setCaseType("warranty")} className={`rounded-xl border p-3 text-left text-sm ${caseType==="warranty"?"border-primary bg-primary/5 text-primary":"border-border text-text"}`}><span className="font-semibold">Garantía</span><span className="mt-1 block text-xs text-muted">Falla, diagnóstico y posible reparación.</span></button><button type="button" onClick={()=>setCaseType("return")} className={`rounded-xl border p-3 text-left text-sm ${caseType==="return"?"border-primary bg-primary/5 text-primary":"border-border text-text"}`}><span className="font-semibold">Devolución</span><span className="mt-1 block text-xs text-muted">Ingreso formal por solicitud de devolución.</span></button></div></div>
      <label className="block"><span className="mb-1 block text-sm font-semibold text-text">Motivo reportado *</span><textarea value={reportedIssue} onChange={e=>setReportedIssue(e.target.value)} rows={4} maxLength={2000} className="w-full rounded-xl border border-border px-4 py-3 text-sm" placeholder="Describe lo que reporta el cliente..."/></label>
      <label className="block"><span className="mb-1 block text-sm font-semibold text-text">Estado físico al recibir</span><textarea value={intakeCondition} onChange={e=>setIntakeCondition(e.target.value)} rows={3} maxLength={2000} className="w-full rounded-xl border border-border px-4 py-3 text-sm" placeholder="Golpes, rayones, accesorios recibidos, cargador, etc."/></label>
      <label className="block"><span className="mb-1 block text-sm font-semibold text-text">Evidencias por URL</span><textarea value={evidenceText} onChange={e=>setEvidenceText(e.target.value)} rows={3} className="w-full rounded-xl border border-border px-4 py-3 text-sm" placeholder="Una URL por línea (máximo 12)"/><span className="mt-1 block text-xs text-muted">{evidenceUrls.length}/12 evidencias. En esta fase se registran enlaces; no se crea un bucket nuevo ni se cambia Storage.</span></label>
    </section>
    <div className="flex gap-2"><Link href={`/admin/ventas/${origin.saleId}`} className="flex-1 rounded-xl border border-border py-3 text-center text-sm font-semibold text-text">Cancelar</Link><button type="button" onClick={()=>void submit()} disabled={!canOpen||submitting} className="flex-1 rounded-xl bg-primary py-3 text-sm font-semibold text-white disabled:opacity-40">{submitting?"Abriendo...":caseType==="warranty"?"Abrir garantía":"Abrir devolución"}</button></div>
  </div>;
}
